// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: echo-api.proto

/*
Package echo_api is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package echo_api

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray

func request_EchoAPI_EchoV1_0(ctx context.Context, marshaler runtime.Marshaler, client EchoAPIClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq EchoV1Request
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["text"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "text")
	}

	protoReq.Text, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "text", err)
	}

	msg, err := client.EchoV1(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_EchoAPI_EchoV1_0(ctx context.Context, marshaler runtime.Marshaler, server EchoAPIServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq EchoV1Request
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["text"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "text")
	}

	protoReq.Text, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "text", err)
	}

	msg, err := server.EchoV1(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterEchoAPIHandlerServer registers the http handlers for service EchoAPI to "mux".
// UnaryRPC     :call EchoAPIServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
func RegisterEchoAPIHandlerServer(ctx context.Context, mux *runtime.ServeMux, server EchoAPIServer) error {

	mux.Handle("GET", pattern_EchoAPI_EchoV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/echo_api.EchoAPI/EchoV1")
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_EchoAPI_EchoV1_0(rctx, inboundMarshaler, server, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_EchoAPI_EchoV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterEchoAPIHandlerFromEndpoint is same as RegisterEchoAPIHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterEchoAPIHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterEchoAPIHandler(ctx, mux, conn)
}

// RegisterEchoAPIHandler registers the http handlers for service EchoAPI to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterEchoAPIHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterEchoAPIHandlerClient(ctx, mux, NewEchoAPIClient(conn))
}

// RegisterEchoAPIHandlerClient registers the http handlers for service EchoAPI
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "EchoAPIClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "EchoAPIClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "EchoAPIClient" to call the correct interceptors.
func RegisterEchoAPIHandlerClient(ctx context.Context, mux *runtime.ServeMux, client EchoAPIClient) error {

	mux.Handle("GET", pattern_EchoAPI_EchoV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/echo_api.EchoAPI/EchoV1")
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_EchoAPI_EchoV1_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_EchoAPI_EchoV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_EchoAPI_EchoV1_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}, []string{"v1", "echo", "text"}, ""))
)

var (
	forward_EchoAPI_EchoV1_0 = runtime.ForwardResponseMessage
)
